# Generated by Django 5.0.2 on 2024-04-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='name',
            field=models.CharField(default='bleh', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriber',
            name='phone',
            field=models.CharField(default='bleh', max_length=255),
            preserve_default=False,
        ),
    ]
